version: '2'

volumes: 
  build: 
    driver: local
  cache:
    external: true

services: 
  test:  
    build: 
      context: ../../
      dockerfile: docker/dev/DockerFile
    volumes: 
      - cache:/cache
      - build:/build
    links: 
      - db
    environment: 
      DJANGO_SETTINGS_MODULE: restaurants_admin.settings.test
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      TEST_OUTPUT_DIR: /reports
    command: ["python","manage.py","test","api.tests","--noinput"]
    depends_on:
     - db
    restart: always
  
  builder:
    build: 
      context: ../../
      dockerfile: docker/dev/DockerFile
    volumes: 
      - build:/build
    entrypoint: "entrypoint.sh"
    command: ["pip","wheel","--no-index","-f /build","."]
  
  db:
    image: mysql:5.6
    hostname: db
    expose: 
      - "3306"
    environment: 
      MYSQL_ROOT_PASSWORD: password


      