app:
  build: ../../
  dockerfile: docker/release/Dockerfile
  links: 
    - db
  volumes_from: 
    - webroot
  environment: 
    DJANGO_SETTINGS_MODULE: restaurants_admin.settings.release
    MYSQL_HOST: db
    MYSQL_USER: todo
    MYSQL_PASSWORD: password
  command: 
    - uwsgi
    - --socket /var/www/restaurants_admin/restaurants_admin.sock
    - --chmod-socket=666
    - --module restaurants_admin.wsgi
    - --master
    - --die-on-term

test:
  image: 2251985/restaurants_admin-specs
  links: 
    - nginx
  environment: 
    URL: http://nginx:8000/todos
    JUNIT_REPORT_PATH: /reports/acceptance.xml
  command: --reporter mocha-jenkins-reporter

nginx: 
  build: .
  dockerfile: Dockerfile.nginx
  links: 
    - app
  volumes: 
    - ./restaurants_admin.conf:/etc/nginx/conf.d/restaurants_admin.conf
  ports: 
    - "8000:8000"
  volumes_from: 
    - webroot
     
webroot:
  build: ../../
  dockerfile: docker/release/Dockerfile
  volumes: 
    - /var/www/restaurants_admin
  entrypoint: "true"

db:
  image: mysql:5.6
  expose: 
    - "3306"
  environment: 
    MYSQL_DATABASE: restaurants_admin
    MYSQL_USER: todo
    MYSQL_PASSWORD: password
    MYSQL_ROOT_PASSWORD: password

agent:
  image: 2251985/docker-ansible
  links: 
    - db
  environment: 
    PROBE_HOST: db
    PROBE_PORT: "3306"
  command: ["probe.yml"]