version: '2'

volumes: 
  webroot:
    driver: local

services: 
  app:
    build: 
      context: ../../
      dockerfile: docker/release/Dockerfile
    links: 
      - db
    volumes: 
      - webroot:/var/www/restaurants_admin
    environment: 
      DJANGO_SETTINGS_MODULE: restaurants_admin.settings.release
      MYSQL_DATABASE: restaurants_db
      MYSQL_HOST: db
      MYSQL_USER: api
      MYSQL_PASSWORD: password
    command: 
      - uwsgi
      - --socket /var/www/restaurants_admin/restaurants_admin.sock
      - --chmod-socket=666
      - --module restaurants_admin.wsgi
      - --master
      - --die-on-term
    depends_on:
     - db
    restart: always

  test:
    image: 2251985/restaurants_admin-specs
    links: 
      - nginx
    environment: 
      URL: http://nginx:8000/api
      JUNIT_REPORT_PATH: /reports/acceptance.xml
    command: --reporter mocha-jenkins-reporter

  nginx: 
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    links: 
      - app
    ports: 
      - "8000:8000"
    volumes: 
      - webroot:/var/www/restaurants_admin

  db:
    image: mysql:5.6
    hostname: db
    expose: 
      - "3306"
    environment: 
      MYSQL_DATABASE: restaurants_db
      MYSQL_USER: api
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  agent:
    image: 2251985/docker-ansible
    links: 
      - db
    environment: 
      PROBE_HOST: db
      PROBE_PORT: "3306"
    command: ["probe.yml"]
